"""empty message

Revision ID: 84b399b44743
Revises: 
Create Date: 2025-12-05 23:21:39.749009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84b399b44743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name_category')
    )
    op.create_table('ingredient',
    sa.Column('id_ingredient', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('volume_to_mass_factor', sa.Float(), nullable=True),
    sa.Column('unit_to_mass_factor', sa.Float(), nullable=True),
    sa.Column('nutrition_base_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('calories_per_100', sa.Float(), nullable=False),
    sa.Column('protein_per_100', sa.Float(), nullable=False),
    sa.Column('carbs_per_100', sa.Float(), nullable=False),
    sa.Column('fat_per_100', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_ingredient'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=50), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipe',
    sa.Column('id_recipe', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=125), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'DIFFICULT', name='difficultyenum'), nullable=False),
    sa.Column('preparation_time_min', sa.Integer(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('nutritional_data', sa.Text(), nullable=True),
    sa.Column('nutritional_data_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('state_recipe', sa.Enum('PENDING', 'PUBLISHED', 'REJECTED', name='staterecipeenum'), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id_category'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_recipe'),
    sa.UniqueConstraint('title')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id_recipe'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_favorites',
    sa.Column('id_favorite', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id_recipe'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorite'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe_favorite')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id_recipe_ingredient', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_measure', sa.Enum('KILOGRAMS', 'GRAMS', 'POUNDS', 'OUNCES', 'LITERS', 'MILLILITERS', 'CUPS', 'TABLESPOONS', 'TEASPOONS', 'UNITS', 'PINCH', name='unitenum'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_catalog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_catalog_id'], ['ingredient.id_ingredient'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id_recipe'], ),
    sa.PrimaryKeyConstraint('id_recipe_ingredient')
    )
    op.create_table('recipe_ratings',
    sa.Column('id_rating', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id_recipe'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ratings')
    op.drop_table('recipe_ingredient')
    op.drop_table('recipe_favorites')
    op.drop_table('comments')
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('ingredient')
    op.drop_table('categories')
    # ### end Alembic commands ###
